use_frameworks!

platform :ios, '8.0'

target 'RSVideoLib_Example' do
  pod 'RSVideoLib', :path => '../'

  target 'RSVideoLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
